language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools
  - sudo apt-get install -y sox
install:
  - pip install -r requirements.txt
script:
  - cd ./tests
  - ls
  - python full.py furelise.wav
